spring:
  profiles:
    active:
    - dev
---
server:
  port: 8101
hnuspringcloud:
  hello: dev-v0.1
spring:
  profiles: dev
  application:
    name: hnuspringcloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka:7001/eureka,http://eureka2:7002/eureka,http://eureka3:7003/eureka
  instace:
    prefer-ip-address: true
    instance-id: config-client-dev
---
server:
  port: 8102
hnuspringcloud:
  hello: test-v0.5
spring:
  profiles: test
  application:
    name: hnuspringcloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka:7001/eureka,http://eureka2:7002/eureka,http://eureka3:7003/eureka
  instace:
    prefer-ip-address: true
    instance-id: config-client-test


